### ISSUE TITLE
Try use web?

### ISSUE THREAD

**Issue by cyxnzb** [victorrossh/Shop#2]
I think u  can combine this with website

**Comment by victorrossh** [comment]
This plugin wasn't made by me, I just modified it for my server. It was created by MrShark45, and it's also available on his GitHub. However, I'm curious to know what your idea is for using this on a website. You can view the original repository by clicking on the [link](https://github.com/human416c6578/shop).

(Sorry for accidentally modifying your comment, but I have already reverted it to the original version.)

**Comment by cyxnzb** [comment]
> This plugin wasn't made by me, I just modified it for my server. It was created by MrShark45, and it's also available on his GitHub. However, I'm curious to know what your idea is for using this on a website.

I think it's easy to operate the store through the web.In China, there are platforms like this, such as 175 Battle Platform, Douke Battle Platform, and they can all buy the corresponding things on the website and then use them in the game

**Comment by victorrossh** [comment]
I've never seen this before, could you show me?

This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?

That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.

Why is this used in China? Is there something specific that makes it work this way?

**Comment by cyxnzb** [comment]
> I've never seen this before, could you show me?
> 
> This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?
> 
> That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.
> 
> Why is this used in China? Is there something specific that makes it work this way?

To be honest, the main reason is that players can buy better.This is the store URL of the 175 battle platform: http://shop.175pt.com/ This is the store URL of the Dooke battle platform: https://cs.dokee.cn/shop/  This is the store URL of the RedTea battle platform: https://market.tianzebbs.com/ Maybe you need to use a translator to understand the specifics

**Comment by victorrossh** [comment]
> > I've never seen this before, could you show me?
> > This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?
> > That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.
> > Why is this used in China? Is there something specific that makes it work this way?
> 
> To be honest, the main reason is that players can buy better.This is the store URL of the 175 battle platform: http://shop.175pt.com/ This is the store URL of the Dooke battle platform: https://cs.dokee.cn/shop/ This is the store URL of the RedTea battle platform: https://market.tianzebbs.com/ Maybe you need to use a translator to understand the specifics

Alright, but I still haven't quite understood how the plugin works when integrated with the website... After purchasing an item on the site, how does the player receive it in-game?

Also, is the purchase made using coins earned through gameplay, real money, or some other method?

**Comment by victorrossh** [comment]
> > I've never seen this before, could you show me?
> > This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?
> > That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.
> > Why is this used in China? Is there something specific that makes it work this way?
> 
> To be honest, the main reason is that players can buy better.This is the store URL of the 175 battle platform: http://shop.175pt.com/ This is the store URL of the Dooke battle platform: https://cs.dokee.cn/shop/ This is the store URL of the RedTea battle platform: https://market.tianzebbs.com/ Maybe you need to use a translator to understand the specifics

Alright, but I still haven't quite understood how the plugin works when integrated with the website... After purchasing an item on the site, how does the player receive it in-game?

Also, is the purchase made using coins earned through gameplay, real money, or some other method?

**Comment by cyxnzb** [comment]
> 所有者



> > > I've never seen this before, could you show me?
> > > This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?
> > > That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.
> > > Why is this used in China? Is there something specific that makes it work this way?
> > 
> > 
> > To be honest, the main reason is that players can buy better.This is the store URL of the 175 battle platform: http://shop.175pt.com/ This is the store URL of the Dooke battle platform: https://cs.dokee.cn/shop/ This is the store URL of the RedTea battle platform: https://market.tianzebbs.com/ Maybe you need to use a translator to understand the specifics
> 
> Alright, but I still haven't quite understood how the plugin works when integrated with the website... After purchasing an item on the site, how does the player receive it in-game?
> 
> Also, is the purchase made using coins earned through gameplay, real money, or some other method?

As I understand it, it should be through the database and then the currency in which the player buys it is real money

**Comment by cyxnzb** [comment]
> > > I've never seen this before, could you show me?
> > > This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?
> > > That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.
> > > Why is this used in China? Is there something specific that makes it work this way?
> > 
> > 
> > To be honest, the main reason is that players can buy better.This is the store URL of the 175 battle platform: http://shop.175pt.com/ This is the store URL of the Dooke battle platform: https://cs.dokee.cn/shop/ This is the store URL of the RedTea battle platform: https://market.tianzebbs.com/ Maybe you need to use a translator to understand the specifics
> 
> Alright, but I still haven't quite understood how the plugin works when integrated with the website... After purchasing an item on the site, how does the player receive it in-game?
> 
> Also, is the purchase made using coins earned through gameplay, real money, or some other method?

Some servers have such a mechanism, such as the zombie server, killing zombies will drop virtual items they call materials, and players can collect materials to craft weapons in the menu, just like Minecraft, but everything is displayed in text. Once crafted, it can be seen in the in-game backpack

**Comment by victorrossh** [comment]
> > > > I've never seen this before, could you show me?
> > > > This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?
> > > > That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.
> > > > Why is this used in China? Is there something specific that makes it work this way?
> > > 
> > > 
> > > To be honest, the main reason is that players can buy better.This is the store URL of the 175 battle platform: http://shop.175pt.com/ This is the store URL of the Dooke battle platform: https://cs.dokee.cn/shop/ This is the store URL of the RedTea battle platform: https://market.tianzebbs.com/ Maybe you need to use a translator to understand the specifics
> > 
> > 
> > Alright, but I still haven't quite understood how the plugin works when integrated with the website... After purchasing an item on the site, how does the player receive it in-game?
> > Also, is the purchase made using coins earned through gameplay, real money, or some other method?
> 
> Some servers have such a mechanism, such as the zombie server, killing zombies will drop virtual items they call materials, and players can collect materials to craft weapons in the menu, just like Minecraft, but everything is displayed in text. Once crafted, it can be seen in the in-game backpack

This is interesting, but it's not something I'm looking for at the moment... I don't think this fits with my servers, especially with the mods I have. This is more interesting for zombie servers. I imagine you're a zombie mode player, right? or do you also play KZ / Bhop?

**Comment by cyxnzb** [comment]
> > > > > I've never seen this before, could you show me?
> > > > > This seems interesting, but it's not very practical... Would the player have to go to the website every time to buy a new item?
> > > > > That would completely remove the convenience, forcing the player to minimize the game and open the website... instead of being able to buy directly within the game.
> > > > > Why is this used in China? Is there something specific that makes it work this way?
> > > > 
> > > > 
> > > > To be honest, the main reason is that players can buy better.This is the store URL of the 175 battle platform: http://shop.175pt.com/ This is the store URL of the Dooke battle platform: https://cs.dokee.cn/shop/ This is the store URL of the RedTea battle platform: https://market.tianzebbs.com/ Maybe you need to use a translator to understand the specifics
> > > 
> > > 
> > > Alright, but I still haven't quite understood how the plugin works when integrated with the website... After purchasing an item on the site, how does the player receive it in-game?
> > > Also, is the purchase made using coins earned through gameplay, real money, or some other method?
> > 
> > 
> > Some servers have such a mechanism, such as the zombie server, killing zombies will drop virtual items they call materials, and players can collect materials to craft weapons in the menu, just like Minecraft, but everything is displayed in text. Once crafted, it can be seen in the in-game backpack
> 
> This is interesting, but it's not something I'm looking for at the moment... I don't think this fits with my servers, especially with the mods I have. This is more interesting for zombie servers. I imagine you're a zombie mode player, right? or do you also play KZ / Bhop?

I'm sorry I didn't reply to your message in time, I've been working on zombie mode for almost 11 years, so of course I'm a zombie mode player, I just want to make the server more interesting, but I don't know how to implement the code
